name: Release

on:
  push:
    tags:
      - 'v*' # Запускается при пуше тегов, начинающихся с 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Полная история коммитов для работы с тегами

      - name: Установка JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Идентификатор сервера для публикации
          settings-path: ${{ github.workspace }} # Путь к настройкам Maven

      - name: Выдача прав на выполнение gradlew
        run: chmod +x gradlew

      - name: Сборка и публикация
        run: ./gradlew build publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Токен для публикации в GitHub Packages

      - name: Создание релиза на GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }} # Используем созданный тег
          name: Release ${{ github.ref_name }}
          body: |
            Автоматический релиз для версии ${{ github.ref_name }}
            - Собран и опубликован артефакт в GitHub Packages
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}