name: Version Bump and Release

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      version_part:
        description: 'Какую часть версии увеличить?'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version-bump:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Настройка пользователя Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Определение типа увеличения версии
        id: version_type
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "type=${{ github.event.inputs.version_part }}" >> $GITHUB_OUTPUT
          else
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Получение текущей версии
        id: current_version
        run: |
          VERSION=$(cat version | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          CLEAN_VERSION=$(echo "$VERSION" | sed 's/-SNAPSHOT$//')
          echo "clean_version=$CLEAN_VERSION" >> $GITHUB_OUTPUT

      - name: Расчет следующей версии
        id: next_version
        run: |
          CURRENT_VERSION="${{ steps.current_version.outputs.clean_version }}"
          VERSION_PART="${{ steps.version_type.outputs.type }}"
          
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]:-0}
          MINOR=${VERSION_PARTS[1]:-0}
          PATCH=${VERSION_PARTS[2]:-0}
          
          case $VERSION_PART in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch|*)
              PATCH=$((PATCH + 1))
              ;;
          esac
          
          NEXT_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Обновление файла версии
        run: |
          echo "${{ steps.next_version.outputs.version }}-SNAPSHOT" > version

      - name: Коммит и пуш обновления версии
        run: |
          git add version
          git commit -m "Bump version to ${{ steps.next_version.outputs.version }}-SNAPSHOT [skip ci]"
          git push origin master

      - name: Создание и пуш тега
        run: |
          TAG_NAME="v${{ steps.next_version.outputs.version }}"
          git tag -a $TAG_NAME -m "Release version ${{ steps.next_version.outputs.version }}"
          git push origin $TAG_NAME

      - name: Установка JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Выдача прав на выполнение gradlew
        run: chmod +x gradlew

      - name: Сборка проекта
        run: ./gradlew build

      - name: Публикация в GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Создание релиза на GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.next_version.outputs.version }}
          name: Release v${{ steps.next_version.outputs.version }}
          body: |
            Автоматический релиз для версии v${{ steps.next_version.outputs.version }}
            
            ## Что нового
            - Собран и опубликован артефакт в GitHub Packages
            - Версия: v${{ steps.next_version.outputs.version }}
            
            ## Как использовать
            ```gradle
            repositories {
                maven {
                    url 'https://maven.pkg.github.com/${{ github.repository }}'
                    credentials {
                        username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                        password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
                    }
                }
            }
            
            dependencies {
                implementation 'ваш_группа:ваш_артефакт:v${{ steps.next_version.outputs.version }}'
            }
            ```
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}